name: Update Unity DLLs

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of Unity to download, defaults to the latest
        type: string
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  extractUnity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: repo
    
      - name: Get Unity version
        if: inputs.version == ''
        run: |
          read -r CI_UNITY_VERSION CI_UNITY_CHANGESET <<< "$(npx --yes unity-changeset list | head -n 1 | tr -d '\n')"
      
      - name: Get Unity changeset
        if: inputs.version != ''
        run: |
          CI_UNITY_VERSION='${{ inputs.version }}'
          CI_UNITY_CHANGESET=$(npx --yes unity-changeset "$CI_UNITY_VERSION")
          
      - run: |
          echo $CI_UNITY_VERSION
          echo $CI_UNITY_CHANGESET
          echo 1
          npx --yes unity-changeset list
          echo 2
          npx --yes unity-changeset list | head -n 1 | tr -d '\n'
          read -r CI_UNITY_VERSION CI_UNITY_CHANGESET <<< $'2022.2.17f1	54cb9bda89c4\n'
          echo $CI_UNITY_VERSION
          echo $CI_UNITY_CHANGESET
          read -r CI_UNITY_VERSION CI_UNITY_CHANGESET <<< "$(npx --yes unity-changeset list | head -n 1 | tr -d '\n')"
          echo $CI_UNITY_VERSION
          echo $CI_UNITY_CHANGESET
          exit 1

      - name: Download and extract DLLs from Unity
        run: |
          wget -nv "https://download.unity3d.com/download_unity/$CI_UNITY_CHANGESET/LinuxEditorInstaller/Unity.tar.xz"
          tar -xf Unity.tar.xz
          mkdir extracted
          mv Editor/Data/Managed/UnityEngine.dll extracted
          mv Editor/Data/Managed/UnityEngine.pdb extracted
          mv Editor/Data/Managed/UnityEngine/UnityEngine.CoreModule.dll extracted
          mv Editor/Data/Managed/UnityEngine/UnityEngine.SharedInternalsModule.dll extracted
        
      - name: Upload DLLs as a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Extracted DLLs
          path: extracted
          if-no-files-found: error
        
      - name: Add extracted files to repo
        run: mv -f extracted/* repo/SampleMod/Lib

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5.0.1
        with:
          path: repo
          commit-message: Update Unity DLLs to version ${{ env.CI_UNITY_VERSION }}
          branch: updated-unity-dlls
          title: Update Unity DLLs to ${{ env.CI_UNITY_VERSION }}
          body: Unity DLLs extracted from Unity version `${{ env.CI_UNITY_VERSION }}` changeset `${{ env.CI_UNITY_CHANGESET }}`, triggered by @${{ github.actor }}.
          delete-branch: true
