name: Update Unity DLLs

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of Unity to download, defaults to the latest
        type: string
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  extractUnity:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v3
    
      - name: Get Unity version
        if: inputs.version == ''
        run: |
          IFS=" " read -r CI_UNITY_VERSION CI_UNITY_CHANGESET <<< "$(npx --yes unity-changeset list | head -n 1)"
      
      - name: Get Unity changeset
        if: inputs.version != ''
        run: |
          CI_UNITY_VERSION='${{ inputs.version }}'
          CI_UNITY_CHANGESET=$(npx --yes unity-changeset "$CI_UNITY_VERSION")
          
      - name: Download and extract DLLs from Unity
        run: |
          wget -nv "https://download.unity3d.com/download_unity/$CI_UNITY_CHANGESET/LinuxEditorInstaller/Unity.tar.xz"
          tar -xf Unity.tar.xz
          mkdir DLLs
          mv Editor/Data/Managed/UnityEngine.dll DLLs
          mv Editor/Data/Managed/UnityEngine.pdb DLLs
          mv Editor/Data/Managed/UnityEngine/UnityEngine.CoreModule.dll DLLs
          mv Editor/Data/Managed/UnityEngine/UnityEngine.SharedInternalsModule.dll DLLs
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Extracted DLLs
          path: DLLs
          if-no-files-found: error
